### ISSUE TITLE
No issues, Just thankyou.

### ISSUE THREAD

**Issue by Faisal-Manzer** [sjkingo/django-ebhealthcheck#1]
Hi, this package saved my day. I spent almost two days in this `400`. This package is awesome.

**Comment by sjkingo** [comment]
Recently I have been handling this at the web server level instead of letting the app hit it. e.g. nginx:

```
location /healthcheck/ {
    return 204;
}
```

You obviously lose the red/green status of the app itself, but there is other tooling that can handle this and drain the target if needed.

**Comment by darajnish** [comment]
Thanks a lot for this package. I was having a hard time trying to figure out how to inject `ip -4 addr show dev eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'` inside the docker environment variables and pick it up in django and push it into `DJANGO_ALLOWED_HOSTS` to get around with the 400 requests. But, this package saved my life. Thanks!

**Comment by omarryhan** [comment]
Just Works ™️

Awesome job!

**Comment by sjkingo** [comment]
I'm glad you found it useful!
